// swift-tools-version:5.9
//
// FantasticKernel — Swift Package wrapping Fantastic.xcframework.
//
// Consume from an Xcode project / project.yml:
//     dependencies: [
//         .package(path: "../rust/packaging/FantasticKernel"),
//     ]
//     targets: [
//         .target(name: "Fantastic_Lite", dependencies: [
//             .product(name: "FantasticKernel", package: "FantasticKernel"),
//         ]),
//     ]
//
// The XCFramework is built by `rust/scripts/build-xcframework.sh`.
// Run that before `swift build` or before opening the host Xcode
// project on a fresh checkout — `Fantastic.xcframework/` is checked
// in as a release artifact, not regenerated by SPM itself.

import PackageDescription

let package = Package(
    name: "FantasticKernel",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
    ],
    products: [
        .library(
            name: "FantasticKernel",
            targets: ["FantasticKernel"]
        ),
    ],
    targets: [
        // The Swift wrapper layer (re-exports the UniFFI-generated
        // bindings + any Swift-side conveniences).
        .target(
            name: "FantasticKernel",
            dependencies: ["FantasticUniFFI"],
            path: "Sources/FantasticKernel"
        ),

        // The binary XCFramework that ships the Rust kernel.
        .binaryTarget(
            name: "FantasticUniFFI",
            path: "Fantastic.xcframework"
        ),
    ]
)
